language: node_js
node_js:
  - "lts/*"
  - "node"
  - "4"
cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn lint
  - yarn build
  - node lib

notifications:
  email:
    on_success: never
    on_failure: change
